---
- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    ec2_access_key:
    ec2_secret_key:
    ec2_region: us-east-1
    ec2_image: ami-ce5d04b4
    ec2_instance_type: t2.micro
    ec2_keypair: centos
    ec2_security_group: WebDMZVPCcloud
    ec2_instance_count: 1
    ec2_tag: demo_video
    wait_for_port: 22

  tasks:
  - name: Launch AWS instances
    ec2: >
     access_key="{{ ec2_access_key }}"
     secret_key="{{ ec2_secret_key }}"
     keypair="{{ ec2_keypair }}"
     group="{{ ec2_security_group }}"
     type="{{ ec2_instance_type }}"
     image="{{ ec2_image }}"
     region="{{ ec2_region }}"
     instance_tags="{'Name':'{{ ec2_tag }}'}"
     count="{{ ec2_instance_count }}"
     wait=true
    register: ec2

  - name: Add  new instance to host ec2_security_group
    local_action: add_host
      hostname="{{ item.public_ip }}"
    with_items: "{{ ec2.instance }}"

  - name: Wait for SSH come
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
    with_items: "{{ ec2.instance }}"
#  - name: Wait for instances to come up
#    local_action: wait_for port="{{ wait_for_port }}" timeout=600 state=started host="{{ item.public_dns_name }}"
#    with_items: "{{ ec2.instances }}"
