- hosts: app_servers
  tasks:
  - name: gather facts from db servers
    setup:
    delegate_to: "{{item}}"
    delegate_facts: True
    with_items: "{{groups['lb_servers']}}"

  - debug: var=ansible_eth0['ipv4']['address']